core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Default:index }

core_project:
    path:     /
    defaults: { _controller: CoreBundle:Default:project }

core_ressource:
    path:     /
    defaults: { _controller: CoreBundle:Default:ressource }

core_task:
    path:     /
    defaults: { _controller: CoreBundle:Default:task }