core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Default:index }

core_project:
    path:     /project
    defaults: { _controller: CoreBundle:Default:project }

core_resource:
    path:     /resource
    defaults: { _controller: CoreBundle:Default:resource }

core_task:
    path:     /task
    defaults: { _controller: CoreBundle:Default:task }