services:
    dao.project:
        parent: custom_dao
        public: true
        class:  CoreBundle\DAO\ProjectDAO

    dao.task:
        parent: custom_dao
        public: true
        class:  CoreBundle\DAO\TaskDAO