# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        UserBundle\Entity\User: sha512

    #role_hierarchy:


    providers:
        main:
            id: UserBundle\Security\UserProvider

#     Chef de projet, Directeur de projet, Développeur  CP DP DEV

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        register:
            pattern:      ^/register
            anonymous:    ~

        # forgot:
        #     pattern:      ^/resetting
        #     anonymous:   ~

        login:
            pattern:      ^/login$
            anonymous:    ~

        main:
            pattern:      ^/
            anonymous:    false
            provider:     main
            form_login:
                login_path: user_login
                check_path: user_login_check
            logout:
                path:       user_logout
                target:     user_login
            #remember_me:
            #    secret:     '%secret%'

    # activate different ways to authenticate

    # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
    #http_basic: ~

    # https://symfony.com/doc/current/security/form_login_setup.html
    #form_login: ~
 