# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        UserBundle\Entity\Resource.php: sha512

    providers:
        main:
            id: fos_user.user_provider.username

#     Chef de projet, Directeur de projet, Développeur

    firewalls:
        main:
            pattern:      ^/
            anonymous:    true
            provider:     main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     login
            remember_me:
                secret:     %secret%

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    # activate different ways to authenticate

    # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
    #http_basic: ~

    # https://symfony.com/doc/current/security/form_login_setup.html
    #form_login: ~
 