<?php

namespace UserBundle\Repository;

/**
 * ResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceRepository extends \Doctrine\ORM\EntityRepository
{
   public function findProjects($resource)
    {
        $qb = $this->createQueryBuilder('p');

        return $qb
            ->join('p.tasks', 't')
            ->join('t.resources', 'r')
            ->where($qb->expr()->eq('r', ':resource'))

            ->setParameter('resource', $resource)

            ->getQuery()
            ->getResult()
            ;
    }
}
