<?php

namespace UserBundle\Repository;

/**
 * ResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceRepository extends \Doctrine\ORM\EntityRepository
{
   public function findProjects($resource)
    {
      return $this->getEntityManager()
            ->createQuery(
<<<<<<< HEAD
                'SELECT * FROM CoreBundle:projects p INNER JOIN CoreBundle:tasks t ON p.id = t.project_id INNER JOIN resources_tasks ON t.id = resources_tasks.task_id WHERE tasks_users.resources_id = ?1'
            )->setParameter(1, $resource->getId())
=======
                'SELECT p FROM CoreBundle:projects p INNER JOIN CoreBundle:tasks t ON p.id = t.project_id INNER JOIN resources_tasks ON t.id = resources_tasks.task_id WHERE tasks_users.resources_id = ?1'
            )->setParameter(1, $this->getId())
>>>>>>> 5af2f09638cf1d9f5aacaf25b27edc9580c00fc5
            ->getResult();
    }
}
