user_login:
    path:   /login
    defaults:
        _controller: UserBundle:Security:login

user_login_check:
    path:   /login_check

user_register:
    path:   /register
    defaults:
        _controller: UserBundle:Security:register

user_logout:
    path:   /logout
