user_login:
    path:   /login
    defaults:
        _controller: UserBundle:Security:login

user_login_check:
    path:   /login_check

user_register:
    path:   /register
    defaults:
        _controller: UserBundle:Security:register

user_logout:
    path:   /logout

user_delete:
    path:   /user/delete
    defaults:
        _controller: UserBundle:Security:delete

user_edit:
    path:   /user/{id}
    defaults:
        _controller: UserBundle:Security:edit