<?php

namespace CoreBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
  public function findResources()
    {
      return $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM resources INNER JOIN resources_tasks rt ON r.id = rt.user_id INNER JOIN tasks t ON rt.task_id = t.id WHERE t.project_id = ?1'
            )->setParameter(1, $resource->getId())
            ->getResult();
    }

    public function findProjects($resource)
    {
        $qb = $this->createQueryBuilder('p');

        return $qb
            ->join('p.tasks', 't')
            ->join('t.resources', 'r')
            ->where($qb->expr()->eq('r', ':resource'))

            ->setParameter('resource', $resource)

            ->getQuery()
            ->getResult()
            ;
    }
}
