<?php

namespace CoreBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProjects($resource)
    {
        $qb = $this->createQueryBuilder('p');

        return $qb
            ->leftJoin('p.tasks', 't')
            ->leftJoin('t.resources', 'r')

            ->andWhere($qb->expr()->orX(
            	$qb->expr()->eq('r', ':resource'),
            	$qb->expr()->eq('p.responsible', ':resource'),
            	$qb->expr()->eq('p.referent', ':resource')
            ))

            ->setParameter('resource', $resource)

            ->getQuery()
            ->getResult()
            ;
    }
}
