<?php

namespace CoreBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
  public function findResources()
    {
      return $this->getEntityManager()
            ->createQuery(
                'SELECT resources.* r FROM resources INNER JOIN resources_tasks rt ON r.id = rt.user_id INNER JOIN tasks t ON rt.task_id = t.id WHERE t.project_id = ?1'
            )->setParameter(1, $this->getId())
            ->getResult();
    }
}
